#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/credstash.sh

destination=$1
payload=$(mktemp $TMPDIR/credstash-resource-request.XXXXXX)
cat > $payload <&0

table=$(jq -r '.source.table // "credstash"' < $payload)
region=$(jq -r '.source.region // "eu-west-1"' < $payload)
encryption_key=$(jq -r '.source.encryption_key // "alias/credstash"' < $payload)
secrets=($(jq -r '.params.secrets // [] | .[]' < $payload))

echo "INFO: Reading following secrets: ${secrets[*]}"

for secret in "${secrets[@]}"; do
    mkdir -p "${destination}/$(dirname ${secret})"
    get_secret ${table} ${region} ${secret} > ${destination}/${secret}.txt
done

version="{\"date\": \"$(date +%s)\"}"
jq -n "{
  version: ${version}
}" >&3
